Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
Rscript myscript.R > Rout/job-$LAUNCHER_JID.Rout
