R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
R CMD BATCH myscript.R > Rout/job-$LAUNCHER_JID.Rout
