# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('_armatemplate_rcpparma_hello_world', PACKAGE = 'armatemplate')
}

#' My silly function
#' 
#' A longer description, to be includd
#' @title Outer Product 
#' @param x A vector for which the outer product is calculated
#' 
#' @return 
#' \item{First}{my first item}
#' \item{Second}{second element of list}
#' 
#' @examples
#' x <- rnorm(10)
#' rcpparma_outerproduct(x)
#' 
#' @author Spencer Woody
#' 
#' @export
rcpparma_outerproduct <- function(x) {
    .Call('_armatemplate_rcpparma_outerproduct', PACKAGE = 'armatemplate', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_armatemplate_rcpparma_innerproduct', PACKAGE = 'armatemplate', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_armatemplate_rcpparma_bothproducts', PACKAGE = 'armatemplate', x)
}

